### ISSUE TITLE
Draw "active" nodes/links on top of other nodes/links

### ISSUE THREAD

**Issue by mpryor** [jollyjerr/mindgraph#18]
![image](https://github.com/jollyjerr/mindgraph/assets/3487369/6ddfccac-e8aa-466e-bebf-7bf9843c0184)

In the screenshot above, the connection between the "small3" and "med1" nodes appears behind some other connection.

It might be nice to have the currently active nodes/links drawn on "top of" everything else.

To accomplish this, we'd have to essentially emulate a "z-index", sort our drawables by that "z-index" property and then render things with a higher "z-index" last.

**Comment by jollyjerr** [comment]
What do you think about adding the concept of layers here (which are in memory canvases under the hood) rather than sorting? This would also allow us to make opacity updates to the whole bottom layer. Each layer can be drawn with visibleContext.drawImage(inMemoryCanvas)

**Comment by mpryor** [comment]
Just saw this! I think that's a good idea!
