### ISSUE TITLE
logo, branding, and vision

### ISSUE THREAD

**Issue by jollyjerr** [jollyjerr/mindgraph#28]
Spike on where this is all going:

- [ ] What is the dream product for v1?

Our dream mvp product is a saas product where a user can host a read-only version of their markdown notes and they get a bunch of cool features for free:
- graph view of how the notes connect to one another
- search/filter tools
- single page view of notes that looks great on the web
- note navigation (traverse the graph)
- pro SEO out of the box

This saas product should be built out of composable packages so that developers can use pieces of it without actually using the saas product if they wish.

- [ ] What should everything be named? Is mindgraph the right name?

I'm not great at marketing, but I think mindgraph or just "mind" would both be okay. I think a cool tree name like Baobab or Aspen could work as well because it's like a tree data structure sorta and it grows over time.

- [ ] We should create a logo, probs with AI, and make the readmes look super pro

Depends if we go with a tree thing

![laWxwjZXt4VcPFKXQCEz--1--4m1cq](https://github.com/jollyjerr/mindgraph/assets/51095001/3977e45b-d9ed-40c7-b0df-0d22c394eea5)

Or a "mind" thing (this example kinda sucks but you get the idea haha)

![HY2I7fmMHLnTfWYpQqZ1--1--hvvsk](https://github.com/jollyjerr/mindgraph/assets/51095001/c12d8263-1e0c-4ad7-977f-ecd85f703823)

- [ ] How can we break that dream into composable packages?

@mind/common - code that is shared across multiple packages
@mind/read - responsible for all server-side data manipulation. Basically models and controllers.
@mind/graph - responsible for the graph view on canvas
@mind/ui - shared UI code for traversing the graph and showing notes
@mind/react - react specific code for traversing the graph and showing notes
@mind/any_other_framework - same as above
@mind/share - put it all together into a next.js saas product (still open source and could be deployed internally by teams)

- [ ] How will we host our documentation?

Our documentation will be markdown notes and hosted on the sass product? 😄 

- [ ] Split all this thinking into tickets

once we all agree

**Comment by jollyjerr** [comment]
@mpryor I updated the issue description with some thoughts. Interested to hear what you like or would do differently 👀. I also put a pretty minimal MVP up, so feel free to throw out bigger ideas if you have any.

**Comment by mpryor** [comment]
@jollyjerr 

I think this is great!!

## MVP

I have a bunch of other ideas, some that apply to the MVP and some that don't...

Some other things I think we might want to call out in the MVP:
- A unique "URL" for their SaaS hosted notes page - obviating the need for deploying/hosting anywhere else. We could derive this from their username, or allow them to provide their own unique path (as long as it doesn't conflict with someone else's path)
- A really well made landing page 
- The concept of "users", and a way to login (Probably with Oauth w/ Github)?

Should we specify in the MVP that the way we intend to have users host their notes is via Github itself? 
I think using Github as the storage has a lot of implications:
- the need for users/auth 
- do we allow hosting of non-public repos via some sort of Oauth-type federation w/ Github?

## Package breakdown
I think the package breakdown looks solid, I don't really have any concerns with it TBH. Should we create a Github Organization and migrate stuff over to it when we finalize the branding?

## Branding 
Also... I think I'm a big fan of the tree branding idea - I like what you shared, but I made some attempts at riffing on it too... I think this is the best I came up with so far -
![flat-vector-logo-of-an-aspen-tree-where-each-branch-splits-into-2-more-branches-minimal-graphic-by-](https://github.com/jollyjerr/mindgraph/assets/3487369/3fcc07c0-c81a-4d5a-a571-e694a134b9e6)

## Future thoughts
Just spitballing a bunch of thoughts here.... it's going to be a lot but just want somewhere to write this stuff down
- I think MVP comes with a default UI/experience, but long-term it would be really interesting to have enough customization/abstraction in the UI where they can choose different layouts (blog, wiki, notes view, graph view, etc), and each of those layouts could be further customized by our users. Each component could have a bunch of properties that are toggleable/customizable at runtime. One simple example might be that the graph view could have different forces applied on load, or no forces at all. 
- User/Group management. 
- An individuals use-case might just be publishing their notes for the world. This could be a blog, a wiki, programming docs, or just regular ole notes. 
- On top of the individual use-case, we could support enterprise/team use-cases by extending the user concept with groups/RBAC/user management/etc. This could come with "privately" hosted repos that aren't shared to the public but require login, along with group membership to be able to view the notes. 
- Enterprise/team use-cases could be solved through SaaS, but also maybe a self-hosted solution (super long term)
- Ability to edit through our UI - basically a markdown WYSIWYG that could replace the need for users to have/use other editors
- If we have edit, we could extend the team/enterprise features to allow users of a team/organization/etc to share edit access to a single repo.
- Also, allowing edit through the app could potentially introduce some interesting workflows - Leveraging PRs to "approve" content changes by content administrators, etc
- Tagging - ability for users to tag/group notes outside of the repo
- Auto-tagging? - some sort of lexical parsing of the notes to automatically derive tags/categories
- Linking - ability for users to link their notes together to create a shared experience
- Suggested linking?? (hey we see you have similar content to user X, or organization Y - do you want to propose a link?) 
- Explore page as part of core SaaS - allow people to find user content based off recommendations/categories/etc
- Ability for users to publish their content to an "explore" page, or explicitly deny their content from being found on the explore page

**Comment by jollyjerr** [comment]
notree
